services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_PASSWORD: 112005asasa
      POSTGRES_DB: ToDoTest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ToDoTest"]
      interval: 5s
      timeout: 5s
      retries: 10
     
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
  
  nginx:
    image: nginx
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  