services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    shm_size: 128mb
    
    environment:
      POSTGRES_PASSWORD: 94508443r
      POSTGRES_DB: ToDoTest
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
  
  nginx:
    image: nginx
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"