services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_PASSWORD: 112005asasa
      POSTGRES_DB: ToDoTest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ToDoTest"]
      interval: 5s
      timeout: 5s
      retries: 10
     
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
  
  nginx:
    image: nginx
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/go/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

        
  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'      

  