services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_PASSWORD: 112005asasa
      POSTGRES_DB: ToDoTest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ToDoTest"]
      interval: 5s
      timeout: 5s
      retries: 10
     
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
  
  nginx:
    image: nginx
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app


  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/go/app
    env_file:
      - .env
    depends_on:
      #localstack:
        #condition: service_healthy
      db:
        condition: service_healthy
  
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"           
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/data
      - EDGE_PORT=4566
      - PERSISTENCE=1
    volumes:
      - './.localstack:/data'
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      #interval: 5s
      #timeout: 2s
      #retries: 15
  

  minio:
    image: elestio/minio
    #restart: always
    #dns:
    #    - 8.8.8.8
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes:
        - ./minio_data:/data
    environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: adminpassword12345
        MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
        MINIO_SERVER_URL: http://localhost:9000
        MINIO_DEFAULT_BUCKETS: my-test-bucket,file-storage
    command: server --address ":9000" --console-address ":9001" /data


    

    

        
  


  