// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	NoteID      int         `json:"note_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      pgtype.Text `json:"status"`
}
