// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

type Filemeta struct {
	ID          int    `json:"id"`
	ContentType string `json:"content_type"`
	OwnerType   string `json:"owner_type"`
	OwnerID     int    `json:"owner_id"`
	UserID      int    `json:"user_id"`
	Uri         string `json:"uri"`
}

type Note struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Status      string `json:"status"`
	AuthorID    int    `json:"author_id"`
}

type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Usersnote struct {
	UserID int `json:"user_id"`
	NoteID int `json:"note_id"`
}
