// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteUser(ctx context.Context, id int) error
	GetNote(ctx context.Context, arg GetNoteParams) (Note, error)
	GetNotes(ctx context.Context, authorID int) ([]Note, error)
	GetUser(ctx context.Context, id int) (GetUserRow, error)
	GetUserLoginParams(ctx context.Context, username string) (GetUserLoginParamsRow, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserExistsByID(ctx context.Context, id int) (bool, error)
}

var _ Querier = (*Queries)(nil)
