// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	DeleteNote(ctx context.Context, id int) error
	GetNote(ctx context.Context, id int) (Note, error)
	GetNotes(ctx context.Context) ([]Note, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
}

var _ Querier = (*Queries)(nil)
